### ISSUE TITLE
How to install PyPDFLoader with newer versions of Python

### ISSUE THREAD

**Issue by alykhan** [S0NM/chat-with-everything#1]
PyPDFLoader requires Python < 3.5.    How did you manage to install the package as < 3.5 are not supported anymore?

**Comment by S0NM** [comment]
I'm working with Python 3.12.2. Actually, you don't need to use PyPDFLoader because I've used PyPDFLoader of langchain_community package. Please try:
1) Remove PyPDFLoader from requirements and re-run
2) If 1) is not working, please run "pip show langchain_community" to check the version of langchain_community package
My output: Name: langchain-community
Version: 0.2.11
Summary: Community contributed LangChain integrations.
Home-page: https://github.com/langchain-ai/langchain
